// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace EmprestimosLivrosNovo.Domain.Entities;

public partial class Cliente
{
    public int ClienteId { get; set; }

    public string CPF { get; set; }

    public string nome { get; set; }

    public string endereco { get; set; }

    public string cidade { get; set; }

    public string bairro { get; set; }

    public string numero { get; set; }

    public string telefoneCelular { get; set; }

    public string telefoneFixo { get; set; }

    public virtual ICollection<Emprestimo> Emprestimo { get; set; } = new List<Emprestimo>();
}