// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace EmprestimosLivrosNovo.Domain.Entities;

public partial class VwEmprestimoNovo
{
    public long? IdEmprestimo { get; set; }

    public string Cpf { get; set; }

    public string NomeCliente { get; set; }

    public string NomeLivro { get; set; }

    public int? Eidlivro { get; set; }

    public int? Eidcliente { get; set; }

    public DateTime? DataEmprestimo { get; set; }

    public DateTime? DataEntrega { get; set; }

    public bool? Entregue { get; set; }
}